### ISSUE TITLE
Schematic diagram for Whitebox T1 MkII

### ISSUE THREAD

**Issue by Arsalan-Aijaz** [whitebox-labs/whitebox-docs#1]
I would like to interface 2 third-party sensors with the Whitebox T1 MkII. I could interface them via I2C in ports 6-9 but I wanted to know which other ports of the Arduino I can use. It is my understanding that the A0-A5 pins of the Arduino are unused and can be used. Is that correct? Which other pins can be used without interfering with the sensors on the shield?

**Comment by extrapixel** [comment]
@Arsalan-Aijaz this is not the place for support questions. You can find the answer to your question here: https://www.whiteboxes.ch/docs/tentacle/t1-mkII/#/pinout
