### ISSUE TITLE
Question for T3

### ISSUE THREAD

**Issue by SimonFili** [whitebox-labs/whitebox-docs#2]
I have a couple of T3 that I want to connect to ESP32.  Do I need both +5V and +3.3V or could I simply connect 3.3V to the side headers?

**Comment by extrapixel** [comment]
Short answer: yes, you need to connect both. However, if not using a Pi, you might get away with connecting both to 3.3V. Make absolutely sure your 3.3V source can handle the load. The power rails are split up so the power hungry isolators don't have to be powered by the Pi itself but the (external) 5V.
- https://www.whiteboxes.ch/docs/tentacle/t3-mkII/#/pinout
- https://www.whiteboxes.ch/docs/tentacle/t3-mkII/#/power

For follow-up questions please use the contact form on our website - Github is not the place for support questions.

**Comment by extrapixel** [comment]
btw if you came to GitHub because our contact form was broken - sorry about that. It has since been fixed.

**Comment by SimonFili** [comment]
Thanks for the info.  Yes, the contact form was broken.  I was able to connect 2 tentacle with 6 EZO on an ESP32 Tasmota.  All is good.
